version: '3.7'

services:
  php:
    image: php:8.1-fpm
    volumes:
      - './htdocs:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './htdocs:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

      